import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

// All icons from lucide-react with aliases for compatibility
export {
  // Original names
  LayoutGrid,
  Users,
  UserPlus as UserAdd,
  UserMinus,
  UserCog as UsersMultiple,
  Calendar,
  ShieldUser,
  MessageCircle as Chat,
  BarChart3 as Chart,
  Settings,
  Bell,
  Search,
  Filter,
  Plus,
  Edit,
  Trash,
  Eye,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronLeft as ArrowLeft,
  ChevronUp,
  Check,
  X as Close,
  Info as InfoCircle,
  TrendingUp as TrendUp,
  Send,
  LogOut as Logout,
  User,
  Cog,
  CalendarPlus as CalendarAdd,
  MessageSquare as Message,
  MessageSquare as ChatMultiple,
  Clock,
  Download,
  Upload,
  MoreHorizontal,
  MoreVertical,
  Menu,
  XCircle as CloseCircle,
  Image,
  File,
  Stethoscope as Medical,
  PlusCircle as Create,
  Check as Save,
  Phone,
  Video,
  Target,
  Shield,
  Paperclip,
  MapPin,
  Activity,
  Moon,
  ClipboardCheck,
  AlertTriangle as Warning,
  ArrowRight,
  ArrowDown,
  ArrowUp,
  SquarePen,
  Mail,
  Users as MessageMultiple,
  Info,
  TrendingDown as TrendDown,
  Palette,
  Library,
  ClipboardList as Clipboard,
  CircleUser as Soccer,
  Trophy,
  Trophy as Formation,
  FileText,
  Copy,
  PlayCircle,
  FolderPlus,
  Folder,
  FolderOpen,
  Briefcase,
  Dumbbell,
  Printer,
  Footprints,
  Award,
  Pencil,
  FolderClosed,
  CirclePlus,
  BookOpen,
  Move,
  RotateCcw,
  Maximize2,
  ZoomIn,
  ZoomOut,
  Share2,
  Tag,
  Hash,
  Layers,
} from "lucide-react"
