// Nationality / country options for the searchable nationality dropdown.
// Stored value = the string itself (matches the previous free-text field).
// GCC + common Vision7 nationalities floated to the top, then the rest A–Z.
export const NATIONALITIES: string[] = [
  "Saudi Arabia",
  "United Arab Emirates",
  "Kuwait",
  "Qatar",
  "Bahrain",
  "Oman",
  "Yemen",
  "Egypt",
  "Jordan",
  "Syria",
  "Lebanon",
  "Palestine",
  "Iraq",
  "Sudan",
  "India",
  "Pakistan",
  "Bangladesh",
  "Philippines",
  "Indonesia",
  "Nepal",
  "Sri Lanka",
  "United Kingdom",
  "United States",
  "Canada",
  "Australia",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Austria",
  "Azerbaijan",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Cameroon",
  "Chad",
  "China",
  "Colombia",
  "Comoros",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Ethiopia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hungary",
  "Iran",
  "Ireland",
  "Italy",
  "Ivory Coast",
  "Japan",
  "Kazakhstan",
  "Kenya",
  "Kyrgyzstan",
  "Libya",
  "Malaysia",
  "Maldives",
  "Mali",
  "Mauritania",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Somalia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "Uzbekistan",
  "Vietnam",
  "Zimbabwe",
  "Other",
];

/** Options shape for SelectField / Combobox usages. */
export const NATIONALITY_OPTIONS = NATIONALITIES.map((n) => ({ value: n, label: n }));
